- defaults:
    link:
        relink: true
        force: true

- clean: ['~']

- link:
    ~/.dotfiles: ''
    ~/.aliases.docker: 'aliases.docker'
    ~/.aliases: 'aliases.zsh'
    ~/.gitconfig: 'gitconfig'
    ~/.gitignore: 'gitignore'
    ~/.gitmessage: 'gitmessage'
    ~/.git_prompt: 'git_prompt'
    ~/.git_template: 'git_template'
    ~/.vimrc: 'vimrc'
    ~/.vimrc: 'vimrc'
    ~/.vimrc.bundles: 'vimrc.bundles'
    ~/.zshrc: 'zshrc'
    ~/.secret_env_vars.local: 'secret_env_vars.local'
    ~/.tmux.conf: 'tmux.conf'

- shell:
    - [git submodule update --init --recursive, Installing submodules]
    - [sh configure-vim-plug.sh, Configuring vim-plug]

